version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: cart_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - cart_network

  redis:
    image: redis:7.2-alpine
    container_name: cart_redis
    ports:
      - "6379:6379"
    networks:
      - cart_network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: cart_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - cart_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cart_app
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      SPRING_DATA_MONGODB_URI:  ${SPRING_DATA_MONGODB_URI:mongodb://cart_admin:cartPassword123@ac-od1lz4x-shard-00-00.idltrvz.mongodb.net:27017,ac-od1lz4x-shard-00-01.idltrvz.mongodb.net:27017,ac-od1lz4x-shard-00-02.idltrvz.mongodb.net:27017/cart_checkout?authSource=admin&replicaSet=atlas-11i2ik-shard-0&ssl=true}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      JWT_SECRET: ${JWT_SECRET:-change-me-in-production}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS:-86400000}
      JWT_REFRESH_EXPIRATION_MS: ${JWT_REFRESH_EXPIRATION_MS:-604800000}
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    networks:
      - cart_network

volumes:
  mongodb_data:

networks:
  cart_network:
    driver: bridge
